apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mvp-test-component
  namespace: mvp-demo-dev-namespace-tyfp-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/test-images@sha256:f1b5d08282fe9e983d5d0ca32ef42075f23110f0ffddfeb3ed8287037854e757
        name: container-image
        resources: {}
status: {}
